---
 - hosts: servers
   tasks:
   - debug:
       msg: "Hello"
     become: yes

#   - name: Install docker
#     command: "curl -fsSL https://get.docker.com -o get-docker.sh"

#   - command: "bash get-docker.sh"

#   - name: Run and enable docker
#     service:
#       name: docker
#       state: started
#       enabled: true

#   - name: Install or upgrade docker-compose
#     get_url:
#       url : "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64"
#       dest: /usr/local/bin/docker-compose
#       mode: 'a+x'
#       force: yes

   - copy:
       src: /home/admin1/demo5
       dest: /root
     become: yes

   - name: docker-compose down
     docker_compose:
       project_src: /root/demo5
       state: absent
     become: yes

   - name: docker-compose up
     docker_compose:
       project_src: /root/demo5
       build: yes
       state: present
     become: yes

   - cron:
       name: hourly
       job: "/root/demo5/insert_statistics.sh"
     become: yes

